# Generated by Django 3.0.3 on 2020-03-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=50)),
                ('eemail', models.CharField(max_length=50)),
                ('eephone', models.IntegerField()),
                ('epas', models.CharField(max_length=50)),
                ('eadd', models.CharField(max_length=50)),
                ('egen', models.CharField(max_length=10)),
                ('elook', models.CharField(max_length=50)),
            ],
        ),
    ]
