# Generated by Django 3.0.3 on 2020-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200329_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_upload',
            old_name='file_upload',
            new_name='file_uplo',
        ),
        migrations.AlterField(
            model_name='view_room_db',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
