# Generated by Django 3.0.3 on 2020-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200329_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_try',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='view_room_db',
            name='file_upload',
            field=models.CharField(default='', max_length=100),
        ),
    ]
